#+Title: org-notebook-mode

A minor mode for quickly viewing notes in org-mode. This is an attempt at emulating note browsing feature found in apps like evernote desktop, where moving through titles in the "note list" would open the full contents in the "note panel".

* What it can do

When M-x org-notebook-toggle-view= (=\C-c o=) is called and the view mode is toggled on, moving the cursor to a headline will show its content and subtrees in a separate "subtree" window.

While the view mode is off, you can open a subtree window by moving the cursor to a header and calling =M-x org-notebook-subtree-to-indirect-buffer= (=S-<RET>=).

[[https::/github.com/liamst19/org-notebook-mode.git][file:data/org-notebook-mode.gif]]

* Issues

As this is my first attempt at programming in emacs lisp, I expect there to be many problems with the code. So far I've noticed that:

- Splitting windows in the same direction as the subtree buffer seems will lead to an error which stops the mode from functioning.

* Installation and Setup

Perhaps it goes without saying that =org-mode= is required for this to work. To enable,

 1. Copy =org-notebook-mode.el= into emacs load-path.
 2. In the init file (e.g. =.emacs=, =init.el=), add the following:
    
    #+BEGIN_SRC emacs-lisp
    (require 'org-notebook-mode)
    #+END_SRC
    
 3. You can also set the direction of the new window by setting =org-notebook-window-direction= to =right=, =left=, =above=, or =below=.
    
    #+BEGIN_SRC emacs-lisp
    (setq org-notebook-window-direction 'below)
    #+END_SRC
    
    The default direction is set =right=.
