#+Title: org-notebook-mode

This is an attempt at emulating note browsing feature found in apps like evernote desktop app, in emacs, as minor mode for org-mode.

* Features and issues

When toggled on, moving the cursor to a headline will show its content and subtrees in a separate "subtree" window.

[[https::/github.com/liamst19/org-notebook-mode.git][file:data/org-notebook-mode.gif]]

* Installation and Setup

Perhaps it goes without saying that =org-mode= is required for this to work. To enable,

 1. Copy =org-notebook-mode.el= into emacs load-path.
 2. In the init file (e.g. =.emacs=, =init.el=), add the following:
    
    #+BEGIN_SRC emacs-lisp
    (require 'org-notebook-mode)
    #+END_SRC
    
 3. You can also set the direction of the new window by setting =org-notebook-window-direction= to =right=, =left=, =above=, or =below=.
    
    #+BEGIN_SRC emacs-lisp
    (setq org-notebook-window-direction 'below)
    #+END_SRC
    
    The default direction is set =right=.
 4. In an org-mode buffer, =M-x org-notebook-toggle-view= (=\C-c o=) toggles the view mode on and off. While this mode is toggled on, moving the cursor to a header will open a new window, showing its contents.
